name: Java CI

on:
  repository_dispatch:
    types: run-tests
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'
#    - cron:  '0 * * * *' Every Hour
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - addCI
jobs:
  API-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: mvn clean "-Dtest=*APITest" test
      - name: Print Run id
        run: echo $GITHUB_RUN_ID
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,took
          text: API Tests
          channel: '#botcave'
          mention: UL0FCLKLG,UKU444URX, here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()

#
#curl -H "Accept: application/vnd.github.everest-preview+json" \
#  -H "Authorization: token <token>" \
#  --request POST \
#  --data '{"event_type": "run-tests"}' \
#  https://api.github.com/repos/umapps/UMApps-Test/dispatches